#!/bin/bash
#

_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $ANGEL_REPO == "AngelBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $ANGEL_REPO == "AngelBot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    elif [[ $ANGEL_REPO =~ $regex ]]
    then
        if [[ $ANGEL_REPO_BRANCH ]]
        then
            echo "${ANGEL_REPO}/archive/${ANGEL_REPO_BRANCH}.zip"
        else
            echo "${ANGEL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RoZVZhZGVycy9JblZhZGUvYXJjaGl2ZS9tYXN0ZXIuemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="myangelbot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    HELLPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $HELLPATH
    echo "  • Starting AngelBot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m angelbot
}

start_bot
